import turtle

def makeCube(noah):
  noah.right(90)
  noah.fillcolor("blue")
  noah.begin_fill()
  noah.forward(20)
  noah.right(120)
  noah.forward(20)
  noah.right(60)
  noah.forward(20)
  noah.right(120)
  noah.forward(20)
  noah.left(60)
  noah.end_fill()
  noah.fillcolor("dark blue")
  noah.begin_fill()
  noah.forward(20)
  noah.right(120)
  noah.forward(20)
  noah.right(60)
  noah.forward(20)
  noah.right(120)
  noah.forward(20)
  noah.end_fill()
  noah.left(60)
  noah.fillcolor("light blue")
  noah.begin_fill()
  noah.forward(20)
  noah.right(120)
  noah.forward(20)
  noah.right(60)
  noah.forward(20)
  noah.right(120)
  noah.forward(20)
  noah.end_fill()
  noah.penup()
  noah.left(60)
  noah.forward(10)
  noah.left(90)
  noah.forward(35)
  noah.left(90)
  noah.forward(10)
  noah.right(90)
  noah.pendown()
  
def makeRow(noah):
  count = 0
  noah.goto(0,0)
  while count < 5:
    makeCube(noah)
    noah.left(90)
    noah.penup()
    noah.forward(35)
    noah.left(90)
    noah.forward(80)
    noah.right(180)
    noah.pendown()
    makeCube(noah)
    count = count + 1
    
noah = turtle.Turtle()
makeRow(noah)

turtle.exitonclick()
